name: Update GitHub Metrics

on:
  # Schedule daily updates at midnight UTC
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ===============================================
  # JOB 1: LANGUAGES & CODING EXPERTISE
  # ===============================================
  # Creates focused visualization of programming languages and coding patterns
  languages-expertise:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: jvlevinson/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: ""  # No header info - focus purely on languages
          
          # === DETAILED LANGUAGE ANALYSIS ===
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 10  # More languages for expertise demonstration
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data  # Include different code types
          plugin_languages_threshold: 1%  # Show languages that represent at least 1% of usage
          
          # === CODING HABITS & PATTERNS ===
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 30  # Month of data for patterns
          plugin_habits_from: 200  # Analyze more commits for better patterns
          
          # Output configuration
          filename: assets/languages-expertise.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update language expertise metrics"
          config_timezone: America/Chicago
          optimize: svg

  # ===============================================
  # JOB 2: ACTIVITY & CONTRIBUTION PATTERNS
  # ===============================================
  # Shows contribution consistency and recent activity
  activity-contributions:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: jvlevinson/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: activity  # Include basic activity info
          
          # === CONTRIBUTION CALENDAR ===
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  # Show full year for commitment demonstration
          
          # === RECENT ACTIVITY FEED ===
          plugin_activity: yes
          plugin_activity_limit: 8  # More activities for better context
          plugin_activity_days: 21  # 3 weeks of activity
          plugin_activity_timestamps: yes
          plugin_activity_filter: all
          plugin_activity_visibility: public  # Focus on public contributions
          
          # === FOLLOW-UP TRACKING ===
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          
          # Output configuration
          filename: assets/activity-contributions.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update activity and contribution metrics"
          config_timezone: America/Chicago
          optimize: svg

  # ===============================================
  # JOB 3: ACHIEVEMENTS & PROFILE OVERVIEW
  # ===============================================
  # Professional overview with achievements and key stats
  profile-achievements:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: jvlevinson/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, community, repositories, metadata  # Include profile overview
          
          # === ACHIEVEMENTS & RECOGNITION ===
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C  # Include more achievements
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0  # Show all achievements
          
          # === NOTABLE CONTRIBUTIONS ===
          plugin_notable: yes
          plugin_notable_from: organization, user
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, issue, pull_request  # Specify contribution types
          
          # Output configuration
          filename: assets/profile-achievements.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update profile and achievements metrics"
          config_timezone: America/Chicago
          optimize: svg

  # ===============================================
  # JOB 4: REPOSITORY & PROJECT INSIGHTS
  # ===============================================
  # Technical depth and project management metrics
  repository-insights:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: jvlevinson/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: repository  # Use repository-focused template
          base: repositories  # Include repository information
          
          # === CODE VOLUME & REPOSITORY ANALYSIS ===
          plugin_lines: yes
          plugin_lines_history_limit: 2  # Show code evolution over time
          plugin_lines_repositories_limit: 6  # Analyze more repositories
          plugin_lines_sections: repositories, history
          plugin_lines_details: bytes-size, percentage  # Include detailed breakdowns
          
          # === REPOSITORY TRAFFIC (requires admin access) ===
          plugin_traffic: yes
          
          # === REPOSITORY STARS & POPULARITY ===
          plugin_stars: yes
          plugin_stars_limit: 4  # Show top starred repositories
          
          # Output configuration
          filename: assets/repository-insights.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update repository insights metrics"
          config_timezone: America/Chicago
          optimize: svg

  # ===============================================
  # JOB 5: COMPREHENSIVE SUMMARY (OPTIONAL)
  # ===============================================
  # Fallback comprehensive view for external sharing
  comprehensive-summary:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    # Only run this job manually or on main branch pushes
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - uses: jvlevinson/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Simplified versions of key plugins for overview
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 7
          
          # Output configuration
          filename: assets/comprehensive-summary.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update comprehensive summary metrics"
          config_timezone: America/Chicago
          optimize: svg