name: Update GitHub Metrics

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}