name: Update GitHub Metrics

on:
  # Schedule daily updates at midnight UTC
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token stored in secrets
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic configuration
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata

          # Optional: Configure specific plugins
          plugin_lines: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          # Show coding activity and habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Show achievements and notable contributions  
          plugin_achievements: yes
          plugin_achievements_display: detailed

          # Show repository traffic and stars
          plugin_traffic: yes

          # Show most starred repositories
          plugin_repositories: yes
          plugin_repositories_featured: username/repo-name

          # Show contribution calendar in isometric view
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Show recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # Output configuration
          filename: assets/github-metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update metrics"